-- ============================================
-- Beauzead Supabase Database Setup
-- Run each file in order in the Supabase SQL Editor
-- ============================================
--
-- 01_countries.sql      → Countries table + seed data + RLS
-- 02_business_types.sql → Business types table + seed data + RLS
-- 03_functions.sql      → Shared helper functions (update_updated_at, get_my_role)
-- 04_profiles.sql       → Profiles table + signup trigger + RLS
-- 05_seller_kyc.sql     → Seller KYC table + RLS
-- 06_storage.sql        → KYC documents storage bucket + RLS
-- 07_admin_setup.sql    → Admin user creation instructions
--
-- IMPORTANT: Run 03_functions.sql BEFORE 04 & 05 (they depend on it).
-- Run 06_storage.sql via Supabase SQL Editor (needs storage schema access).
-- ============================================
